version: "3"
services:
  mongodb-service:
    image: mongo:4.0.0
    container_name: "mongodb-service"
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    hostname: mongodb-service
  mancala-game-app-service:
    image: mancala-game-app:1.0.0
    container_name: mancala-game-app
    ports:
      - 8080:8080
    links:
      - mongodb-service